version: "3"
services:

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 20  

  chrome70:
    image: selenium/node-chrome:latest
    depends_on:
      - hub
    environment:
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      HUB_HOST: hub

  chrome66:
    image: selenium/node-chrome:3.11.0
    depends_on:
      - hub
    environment:
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      HUB_HOST: hub

  firefox78:
    image: selenium/node-firefox:latest
    depends_on:
      - hub
    environment:
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      HUB_HOST: hub

  firefox59:
    image: selenium/node-firefox:3.11.0
    depends_on:
      - hub
    environment:
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      HUB_HOST: hub